monitor:
  paths:
    - "D:\\studies\\core"
    - "D:\\studies\\research"

  extensions:
    - ".d"
    - ".mzml"
    - ".raw"
    - ".wiff"
    - ".cdf"
    - ".peg"

# to be added - we don't have any converter for these files yet
#    - ".smp"

  storage: "L:\\mzml"
  msconvert: "D:\\tools\\proteowizard\\msconvert.exe"

stasis:
  url: "https://api.metabolomics.us"
  port: "80"

aws:
  bucketName: "data-carrot"

