monitor:
  # Raw data folders to monitor
  paths:
#    - '\\exploris\exploris\data'  # remote windows share
#    - 'C:\my data\to_monitor'  # local drive

  # Raw data type to monitor
  extensions:
    - '.d'
    - '.raw'
    - '.wiff'
    - '.mzml'

  # regex patterns of samples to skip
  skip:
    - '\.scan'
    - '\.~idx2'
    - '\\(?:.*?)?[ _-]?DNU[ _-]?(?:.*?)'
    - '/(?:.*?)?[ _-]?DNU[ _-]?(?:.*?)'
    - 'preinj'
    - 'prerun'
    - 'test'

  # Destination folder of converted files
  storage: 'C:\Windows\Temp'

  # Full path to ProteoWizard msconvert tool
  msconvert: 'C:\tools\pwiz\msconvert.exe'

  # Enables automatic scheduling of converted samples. Options: True, False. Default: False
  schedule: False

  # Enables checking if sample exists in dynamo before conversion. Options: True, False. Default: False
  exists: True

cis:
  url_var: 'PROD_CIS_API_URL'
  api_key_var: 'PROD_CIS_API_TOKEN'

stasis:
  url_var: 'PROD_STASIS_API_URL'
  api_key_var: 'PROD_STASIS_API_TOKEN'

aws:
  bucket_name: 'data-carrot'
