monitor:
  # Raw data folders to monitor
  paths:
    - 'D:\tools\monitor\tmp\raw'

  # Raw data type to monitor
  extensions:
    - '.d'
    - '.raw'
    - '.wiff'
    - '.mzml'

  # regex patterns of samples to skip
  skip:
    - '\.scan'
    - '\.~idx2'
    - '\\(?:.*?)?[ _-]?DNU[ _-]?(?:.*?)'
    - '/(?:.*?)?[ _-]?DNU[ _-]?(?:.*?)'
    - 'preinj'
    - 'prerun'
    - 'test'

  # Destination folder of converted files
  storage: 'D:\tools\monitor\tmp\mzml'

  # Full path to ProteoWizard msconvert tool
  msconvert: 'D:\tools\pwiz\msconvert.exe'

  # Enables automatic scheduling of converted samples. Default: False
  schedule: False

  # Enables checking if sample exists in dynamo before conversion. Default: False
  exists: False

cis:
  url_var: 'TEST_CIS_API_URL'
  api_key_var: 'TEST_CIS_API_TOKEN'

stasis:
  url_var: 'TEST_STASIS_API_URL'
  api_key_var: 'TEST_STASIS_API_TOKEN'

aws:
  bucket_name: 'datatest-carrot'
