monitor:
  paths:
    - "d:\\data"

  extensions:
    - ".d"
    - ".raw"
    - ".wiff"
    - ".mzml"

# regex patterns of samples to skip
  skip:
    - '\.scan'    # chromatogram data file for wiff format
    - '\.~idx2'   # secondary file for wiff format
    - '\\DNU\\'   # DoNotUse folders
    - '/DNU/'     # DoNotUse folders
    - 'preinj'    # preinjections
    - 'prerun'    # preinjections
    - 'test'      # tests

  storage: "d:\\mzml"
  msconvert: "c:\\tools\\pwiz-3.0.20109-5f47a781c\\msconvert.exe"

stasis:
  url_var: "TEST_STASIS_API_URL"
  api_key_var: "TEST_STASIS_API_TOKEN"

aws:
  bucketName: "data-carrot"
