monitor:
  paths:
    - "D:\\studies\\core"
    - "D:\\studies\\research"

  extensions:
    - ".d"
    - ".raw"
    - ".wiff"
    - ".mzml"

  # regex patterns of samples to skip
  skip:
    - '\.scan'
    - '\.~idx2'
    - '\\DNU\\'
    - '/DNU/'
    - 'preinj'
    - 'prerun'
    - 'test'

  storage: "D:\\lunabkup\\mzml"
  msconvert: "D:\\tools\\pwiz-3.0.21209\\msconvert.exe"


stasis:
  url_var: "PROD_STASIS_API_URL"
  api_key_var: "PROD_STASIS_API_TOKEN"

aws:
  bucketName: "data-carrot"
