monitor:
  # Raw data folders to monitor
  paths:
    - "\\\\exploris\\exploris\\data"  # exploris drive
    - "\\\\dnc3br2\\qexactive\\data"  # QE drive

  # Raw data type to monitor
  extensions:
    - ".d"
    - ".raw"
    - ".wiff"
    - ".mzml"

  # regex patterns of samples to skip
  skip:
    - '\.scan'
    - '\.~idx2'
    - '\\DNU(?:.*?)?'
    - '/DNU(?:.*?)?'
    - 'preinj'
    - 'prerun'
    - 'test'

  # Destination folder of converted files
  storage: "C:\\Windows\\Temp"

  # Full path to ProteoWizard msconvert tool
  msconvert: "C:\\tools\\pwiz\\msconvert.exe"

  # Enables automatic scheduling of converted samples. Default: False
  schedule: True

  # Enables checking if sample exists in dynamo before conversion. Default: False
  exists: True

cis:
  url_var: "PROD_CIS_API_URL"
  api_key_var: "PROD_CIS_API_TOKEN"

stasis:
  url_var: "PROD_STASIS_API_URL"
  api_key_var: "PROD_STASIS_API_TOKEN"

aws:
  bucket_name: "data-carrot"
