monitor:
  paths:
    - "d:/data"

  extensions:
    - ".d"
    - ".mzml"
    - ".raw"
    - ".wiff"

  storage: "d:/mzml"
  msconvert: "c:/tools/pwiz-3.0.20109-5f47a781c/msconvert.exe"

stasis:
  url: "https://test-api.metabolomics.us"
  port: "80"

aws:
  bucketName: "wcmc-data-stasis-raw-test"

