monitor:
  paths:
    - "d:/data"

  extensions:
    - ".d"
    - ".raw"
    - ".wiff"
    - ".mzml"

  storage: "d:/mzml"
  msconvert: "c:/tools/pwiz-3.0.20109-5f47a781c/msconvert.exe"

stasis:
  url: "https://test-api.metabolomics.us"

aws:
  bucketName: "data-carrot"
