monitor:
  paths:
    - "/home/diego/tmp"
    - "/home/diego/.carrot_storage"

  extensions:
    - ".d"
    - ".mzml"
    - ".mzxml"
    - ".raw"
    - ".wiff"

# to be added - we don't have any converter for these files yet
#    - ".cdf"
#    - ".peg"
#    - ".txt"
#    - ".smp"

  storage: "/home/diego/.carrot_storage"

stasis:
  url: "https://test-api.metabolomics.us"
  port: "80"

dataform:
  url: "http://luna.fiehnlab.ucdavis.edu"
  port: "9090"
