monitor:
  paths:
    - "c:\\users\\diego\\.carrot_storage\\raw"

  extensions:
    - ".d"
    - ".mzml"
    - ".mzxml"
    - ".raw"
    - ".wiff"
    - ".cdf"
    - ".peg"

# to be added - we don't have any converter for these files yet
#    - ".smp"

  storage: "c:\\users\\diego\\.carrot_storage\\tmp"
  msconvert: "h:\\proteowizard\\msconvert.exe"

stasis:
  url: "https://test-api.metabolomics.us"
  port: "80"

aws:
  bucketName: "data-carrot"
