monitor:
  paths:
    - "D:\\studies\\core"
    - "D:\\studies\\research"

  extensions:
    - ".d"
    - ".raw"
    - ".wiff"
    - ".mzml"
#    - ".cdf"
#    - ".peg"

  skip:
    - ".scan"   # chromatogram data file for wiff format
    - ".~idx2"  # secondary file for wiff format


# to be added - we don't have any converter for these files yet
#    - ".smp"

  storage: "D:\\lunabkup\\mzml"
#  msconvert: "D:\\tools\\pwiz-3.0.21209\\msconvert.exe"
  msconvert: "c:\\tools\\pwiz-3.0.20109-5f47a781c\\msconvert.exe"


stasis:
  url: "https://api.metabolomics.us"
  api_key_var: "PROD_STASIS_API_TOKEN"

aws:
  bucketName: "data-carrot"
