monitor:
  paths:
    - "/home/diego/.carrot_storage/deconvolution"

  extensions:
    - ".d"
    - ".mzml"
    - ".mzxml"
    - ".raw"
    - ".wiff"
    - ".cdf"
    - ".peg"
    - ".txt"

# to be added - we don't have any converter for these files yet
#    - ".smp"

  storage: "/home/diego/.carrot_storage/tmp"

stasis:
  url: "https://test-api.metabolomics.us"
  port: "80"

dataform:
  url: "http://luna.fiehnlab.ucdavis.edu"
  port: "9090"

aws:
  bucketName: "data-carrot"
