service: monitor-resources
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: us-west-2
  deploymentBucket:
    name: resources-monitor

  #required permissions
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:*
          Resource: { "Fn::Join": [ ":", [ "arn:aws:sqs:${self:custom.region}",  "*:*" ] ] }

custom:
  region: ${opt:region, self:provider.region}

  conversionQueue: "MonitorConversionQueue-${sls:stage}"
  uploadQueue: "MonitorUploadQueue-${sls:stage}"
  preprocessingQueue: "MonitorPreprocessingQueue-${sls:stage}"

package:
  patterns:
    - '!.git/**'
    - '!.venv/**'
    - '!.idea/**'
    - '!.pytest_cache/**'
    - '!venv/**'
    - '!test/**'
    - '!tests/**'
    - '!node_modules/**'
    - '!integrationTests/**'

resources:
  Resources:
    # Here goes raw files that need conversion to mzml
    ConversionQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:custom.conversionQueue}
        VisibilityTimeout: 900

    # Here goes mzml files that need uploading to S3
    UploadQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:custom.uploadQueue}
        VisibilityTimeout: 900

    # Here goes files that need preprocessing
    PreprocessingQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:custom.preprocessingQueue}
        VisibilityTimeout: 900
